spring:
    jpa:
        show-sql: true
        hibernate: 
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true              

#logging:
#    level: 
#        org.springframework.security: TRACE
#        org.springframework.web: TRACE 
